In [ ]:
# Created on Oct 12, 2025
# Created by: Afeena
# Purpose: This file answers the business questions for the user slice

import pandas as pd
import numpy as np
import os as os
import statsmodels.formula.api as smf

# File Paths
UserSeveritySlicePath = "C:\\Users\\afeen\\Documents\\MBAI\\Business Analytics\\FlaskProjects\\Master Code (BA)\\04Regression\\UserSeveritySlice.csv"
destinationFolder = "C:\\Users\\afeen\\Documents\\MBAI\\Business Analytics\\FlaskProjects\\Master Code (BA)\\04Regression"

# Read the CSV file
dfUser = pd.read_csv(UserSeveritySlicePath, low_memory=False)

# Make column for SevereInjury:Fatal/Major = 1, Minor/Minimal = 0
dfUser['SevereInjury'] = np.where(dfUser['SeverityOfInjury'].isin(['Fatal', 'Major']), 1, 0)

# print(df['SeverityOfInjury'].value_counts())
# print(df['SevereInjury'].value_counts())

# identify dummy variable columns
userInvTypeCols = ["UserInvType_Cyclist",
"UserInvType_Cyclist_Passenger",
"UserInvType_Driver___Not_Hit",
"UserInvType_In_Line_Skater",
"UserInvType_Moped_Driver",
"UserInvType_Moped_Passenger",
"UserInvType_Motorcycle_Driver",
"UserInvType_Motorcycle_Passenger",
"UserInvType_Other",
"UserInvType_Passenger",
"UserInvType_Pedestrian",
"UserInvType_Truck_Driver",
"UserInvType_Wheelchair"
]
userAgeRangeCols = ["UserAgeRange_0_to_4",
"UserAgeRange_10_to_14",
"UserAgeRange_15_to_19",
"UserAgeRange_25_to_29",
"UserAgeRange_30_to_34",
"UserAgeRange_35_to_39",
"UserAgeRange_40_to_44",
"UserAgeRange_45_to_49",
"UserAgeRange_5_to_9",
"UserAgeRange_50_to_54",
"UserAgeRange_55_to_59",
"UserAgeRange_60_to_64",
"UserAgeRange_65_to_69",
"UserAgeRange_70_to_74",
"UserAgeRange_75_to_79",
"UserAgeRange_80_to_84",
"UserAgeRange_85_to_89",
"UserAgeRange_90_to_94",
"UserAgeRange_Over_95",
"UserAgeRange_unknown"
]

# ModelA: Severity- Involvement Types
formulaA = 'SevereInjury ~ ' + ' + '.join(userInvTypeCols)
modelA = smf.logit(formula=formulaA, data=dfUser).fit()
print("\n Model A: User Involvement Types vs Severe Injuries \n")
print(modelA.summary())

# Save model summary to csv file
with open(os.path.join(destinationFolder, "UserModelA_Stats.csv"), 'w') as f:
    f.write(str(modelA.summary()))

# ModelB: Severity- User Age Ranges
formulaB = 'SevereInjury ~ ' + ' + '.join(userAgeRangeCols)
modelB = smf.logit(formula=formulaB, data=dfUser).fit()
print("\n Model B: User Age Ranges vs Severe Injuries \n")
print(modelB.summary())

# Save model summary to csv file
with open(os.path.join(destinationFolder, "UserModelB_Stats.csv"), 'w') as f:
    f.write(str(modelB.summary()))

# Function for Odds Ratios and Confidence Intervals
# the Odd Ratios and Summary function above will give the same results.
def odds_ratios_and_ci(whichModel):
    params = whichModel.params
    conf = whichModel.conf_int()
    out = pd.DataFrame({
        # Odds Ratios
        "OR": np.exp(params),
        # Confidence Intervals
        "2.5%": np.exp(conf[0]),
        "97.5%": np.exp(conf[1]),
        # p-values
        "pval": whichModel.pvalues
    })
    return out.sort_values(by="OR", ascending=False)

# Predicted probability for each involvement dummy (set one=1, others=0; all other dummies=0)
def group_pred_by_singleton(whichModel, whichColumns, group_name="Group"):
    # create baseline scenario - set all dummy variables to 0 (reference categories). I will turn on what I want to test
    base = {col: 0 for col in whichModel.model.exog_names if col not in ["Intercept"]}
    results = []     # list to store prediction results
    for g in whichColumns:
        scenario = base.copy() # creates a copy
        scenario[g] = 1  # Set only the current group dummy to 1, others stay 0, allowing me to loop through each dummy variable set it to 1 and then leave the others at 0
        prob = whichModel.predict(pd.DataFrame([scenario]))[0]
        results.append({group_name: g, "PredProb_Severe": prob})
    return pd.DataFrame(results).sort_values("PredProb_Severe", ascending=False)

#Print and save Predicted probabilities for Models A and Model B
print("\n=== Predicted probability of severe injury by involvement type ===")
predProb_involvement = group_pred_by_singleton(modelA, userInvTypeCols, group_name="Involvement")
display(predProb_involvement)
predProb_involvement.to_csv(os.path.join(destinationFolder, "UserModelA_Stats.csv"),  mode='a', header=True,index=False)

print("\n=== Predicted probability of severe injury by age range ===")
predProb_age = group_pred_by_singleton(modelB, userAgeRangeCols, group_name="AgeRange")
display(predProb_age)
predProb_age.to_csv(os.path.join(destinationFolder, "UserModelB_Stats.csv"), mode='a', header=True, index=False)

# Print and save outputs of odds ratios
modelA_or_ci = odds_ratios_and_ci(modelA)
print("\n=== Odds Ratios for Model A (involvement type) ===")
display(modelA_or_ci)
modelA_or_ci.to_csv(os.path.join(destinationFolder, "UserModelA_Stats.csv"), mode='a', header=True, index=False)

modelB_or_ci = odds_ratios_and_ci(modelB)
print("\n=== Odds Ratios for Model B (Age Range) ===")
display(modelB_or_ci)
modelB_or_ci.to_csv(os.path.join(destinationFolder, "UserModelB_Stats.csv"), mode='a', header=True, index=False)

involvement dummies: ['UserInvType_Cyclist', 'UserInvType_Cyclist_Passenger', 'UserInvType_Driver___Not_Hit', 'UserInvType_In_Line_Skater', 'UserInvType_Moped_Driver'] ...total: 13
age range dummies: ['UserAgeRange_0_to_4', 'UserAgeRange_10_to_14', 'UserAgeRange_15_to_19', 'UserAgeRange_25_to_29', 'UserAgeRange_30_to_34'] ...total: 20
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.440483
         Iterations: 35

 Model A: User Involvement Types vs Severe Injuries

                           Logit Regression Results
==============================================================================
Dep. Variable:           SevereInjury   No. Observations:                10044
Model:                          Logit   Df Residuals:                    10030
Method:                           MLE   Df Model:                           13
Date:                Sun, 12 Oct 2025   Pseudo R-squ.:                  0.2347
Time:                        12:59:53   Log-Likelihood:                -4424.2
converged:                      False   LL-Null:                       -5781.3
Covariance Type:            nonrobust   LLR p-value:                     0.000
====================================================================================================
                                       coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------
Intercept                            0.2967      0.036      8.334      0.000       0.227       0.367
UserInvType_Cyclist                  3.5383      0.248     14.284      0.000       3.053       4.024
UserInvType_Cyclist_Passenger        0.3964      1.225      0.324      0.746      -2.005       2.798
UserInvType_Driver___Not_Hit       -19.7380   1.67e+04     -0.001      0.999   -3.27e+04    3.26e+04
UserInvType_In_Line_Skater          20.9339   2.04e+04      0.001      0.999   -3.99e+04       4e+04
UserInvType_Moped_Driver             3.0355      1.018      2.981      0.003       1.040       5.031
UserInvType_Moped_Passenger         19.1445   1.67e+04      0.001      0.999   -3.26e+04    3.27e+04
UserInvType_Motorcycle_Driver        3.1547      0.219     14.375      0.000       2.725       3.585
UserInvType_Motorcycle_Passenger     0.5506      0.347      1.587      0.112      -0.129       1.230
UserInvType_Other                   -1.2130      0.837     -1.449      0.147      -2.854       0.428
UserInvType_Passenger               -0.4065      0.058     -6.989      0.000      -0.521      -0.293
UserInvType_Pedestrian               2.6217      0.087     30.039      0.000       2.451       2.793
UserInvType_Truck_Driver            -0.6222      0.260     -2.395      0.017      -1.131      -0.113
UserInvType_Wheelchair              20.9609      1e+04      0.002      0.998   -1.96e+04    1.97e+04
====================================================================================================

c:\Users\afeen\anaconda3\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
c:\Users\afeen\anaconda3\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.564000
         Iterations: 35

 Model B: User Age Ranges vs Severe Injuries

                           Logit Regression Results
==============================================================================
Dep. Variable:           SevereInjury   No. Observations:                10044
Model:                          Logit   Df Residuals:                    10023
Method:                           MLE   Df Model:                           20
Date:                Sun, 12 Oct 2025   Pseudo R-squ.:                 0.02015
Time:                        12:59:53   Log-Likelihood:                -5664.8
converged:                      False   LL-Null:                       -5781.3
Covariance Type:            nonrobust   LLR p-value:                 2.994e-38
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                 0.7955      0.063     12.563      0.000       0.671       0.920
UserAgeRange_0_to_4      -0.8890      0.204     -4.365      0.000      -1.288      -0.490
UserAgeRange_10_to_14     0.2413      0.176      1.368      0.171      -0.104       0.587
UserAgeRange_15_to_19    -0.1589      0.105     -1.514      0.130      -0.365       0.047
UserAgeRange_25_to_29     0.2701      0.095      2.841      0.005       0.084       0.457
UserAgeRange_30_to_34     0.1843      0.100      1.849      0.065      -0.011       0.380
UserAgeRange_35_to_39     0.1533      0.102      1.505      0.132      -0.046       0.353
UserAgeRange_40_to_44     0.2011      0.106      1.896      0.058      -0.007       0.409
UserAgeRange_45_to_49     0.1770      0.105      1.679      0.093      -0.030       0.384
UserAgeRange_5_to_9      -0.4350      0.190     -2.292      0.022      -0.807      -0.063
UserAgeRange_50_to_54     0.2763      0.105      2.621      0.009       0.070       0.483
UserAgeRange_55_to_59     0.3255      0.110      2.948      0.003       0.109       0.542
UserAgeRange_60_to_64     0.5178      0.125      4.153      0.000       0.273       0.762
UserAgeRange_65_to_69     0.5771      0.133      4.346      0.000       0.317       0.837
UserAgeRange_70_to_74     0.7008      0.146      4.807      0.000       0.415       0.986
UserAgeRange_75_to_79     0.7824      0.158      4.968      0.000       0.474       1.091
UserAgeRange_80_to_84     1.0142      0.188      5.386      0.000       0.645       1.383
UserAgeRange_85_to_89     1.4076      0.250      5.632      0.000       0.918       1.897
UserAgeRange_90_to_94     2.4626      0.723      3.404      0.001       1.045       3.880
UserAgeRange_Over_95      5.2821      6.976      0.757      0.449      -8.391      18.955
UserAgeRange_unknown     -0.6338      0.191     -3.319      0.001      -1.008      -0.259
=========================================================================================

=== Predicted probability of severe injury by involvement type ===

                         Involvement  PredProb_Severe
12            UserInvType_Wheelchair     1.000000e+00
3         UserInvType_In_Line_Skater     1.000000e+00
5        UserInvType_Moped_Passenger     1.000000e+00
0                UserInvType_Cyclist     9.788557e-01
6      UserInvType_Motorcycle_Driver     9.692737e-01
4           UserInvType_Moped_Driver     9.655172e-01
10            UserInvType_Pedestrian     9.487496e-01
7   UserInvType_Motorcycle_Passenger     7.000000e-01
1      UserInvType_Cyclist_Passenger     6.666667e-01
9              UserInvType_Passenger     4.725738e-01
11          UserInvType_Truck_Driver     4.193548e-01
8                  UserInvType_Other     2.857143e-01
2       UserInvType_Driver___Not_Hit     3.603674e-09

=== Predicted probability of severe injury by age range ===

                 AgeRange  PredProb_Severe
18   UserAgeRange_Over_95         0.997711
17  UserAgeRange_90_to_94         0.962963
16  UserAgeRange_85_to_89         0.900524
15  UserAgeRange_80_to_84         0.859316
14  UserAgeRange_75_to_79         0.828909
13  UserAgeRange_70_to_74         0.817010
12  UserAgeRange_65_to_69         0.797802
11  UserAgeRange_60_to_64         0.788054
10  UserAgeRange_55_to_59         0.754173
9   UserAgeRange_50_to_54         0.744939
3   UserAgeRange_25_to_29         0.743762
1   UserAgeRange_10_to_14         0.738220
6   UserAgeRange_40_to_44         0.730385
4   UserAgeRange_30_to_34         0.727059
7   UserAgeRange_45_to_49         0.725601
5   UserAgeRange_35_to_39         0.720871
2   UserAgeRange_15_to_19         0.653968
8     UserAgeRange_5_to_9         0.589147
19   UserAgeRange_unknown         0.540323
0     UserAgeRange_0_to_4         0.476636

=== Odds Ratios for Model A (involvement type) ===

c:\Users\afeen\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)

,OR,2.5%,97.5%,pval
UserInvType_Wheelchair,1.268277e+09,0.000000,inf,9.983307e-01
UserInvType_In_Line_Skater,1.234460e+09,0.000000,inf,9.991803e-01
UserInvType_Moped_Passenger,2.062256e+08,0.000000,inf,9.990830e-01
UserInvType_Cyclist,3.440779e+01,21.173987,55.912758,2.762442e-46
UserInvType_Motorcycle_Driver,2.344595e+01,15.249722,36.047371,7.456000e-47
UserInvType_Moped_Driver,2.081081e+01,2.828074,153.139514,2.874459e-03
UserInvType_Pedestrian,1.375895e+01,11.595644,16.325858,3.073746e-198
UserInvType_Motorcycle_Passenger,1.734234e+00,0.878730,3.422630,1.124533e-01
UserInvType_Cyclist_Passenger,1.486486e+00,0.134653,16.409909,7.462901e-01
Intercept,1.345455e+00,1.254760,1.442704,7.837032e-17
UserInvType_Passenger,6.659459e-01,0.594188,0.746370,2.772432e-12
UserInvType_Truck_Driver,5.367868e-01,0.322583,0.893228,1.664093e-02
UserInvType_Other,2.972973e-01,0.057594,1.534624,1.474694e-01
UserInvType_Driver___Not_Hit,2.678406e-09,0.000000,inf,9.990546e-01

=== Odds Ratios for Model B (Age Range) ===

                               OR      2.5%         97.5%          pval
UserAgeRange_Over_95   196.777112  0.000227  1.706203e+08  4.489491e-01
UserAgeRange_90_to_94   11.735660  2.843073  4.844255e+01  6.629349e-04
UserAgeRange_85_to_89    4.086100  2.503719  6.668567e+00  1.777197e-08
UserAgeRange_80_to_84    2.757026  1.906119  3.987785e+00  7.223816e-08
Intercept                2.215470  1.956899  2.508206e+00  3.382374e-36
UserAgeRange_75_to_79    2.186817  1.605978  2.977730e+00  6.778581e-07
UserAgeRange_70_to_74    2.015279  1.514457  2.681719e+00  1.529532e-06
UserAgeRange_65_to_69    1.780955  1.372841  2.310392e+00  1.384712e-05
UserAgeRange_60_to_64    1.678282  1.314427  2.142856e+00  3.284612e-05
UserAgeRange_55_to_59    1.384763  1.115269  1.719379e+00  3.199394e-03
UserAgeRange_50_to_54    1.318292  1.072219  1.620837e+00  8.755288e-03
UserAgeRange_25_to_29    1.310161  1.087354  1.578622e+00  4.503652e-03
UserAgeRange_10_to_14    1.272868  0.900883  1.798448e+00  1.712816e-01
UserAgeRange_40_to_44    1.222763  0.993219  1.505358e+00  5.798345e-02
UserAgeRange_30_to_34    1.202360  0.988962  1.461806e+00  6.451178e-02
UserAgeRange_45_to_49    1.193575  0.970771  1.467517e+00  9.323728e-02
UserAgeRange_35_to_39    1.165698  0.954760  1.423239e+00  1.322195e-01
UserAgeRange_15_to_19    0.853051  0.694391  1.047962e+00  1.300842e-01
UserAgeRange_5_to_9      0.647250  0.446158  9.389767e-01  2.192558e-02
UserAgeRange_unknown     0.530560  0.364888  7.714507e-01  9.048383e-04
UserAgeRange_0_to_4      0.411071  0.275783  6.127250e-01  1.269864e-05