In [14]:
# Created on Oct 10, 2025
# Created by: Afeena
# Purpose: This file answers the business questions for the user slice

import pandas as pd
import numpy as np
import os as os
# import sys
import statsmodels.formula.api as smf
from itertools import product


# File Paths
TimeSeveritySlicePath = "C:\\Users\\afeen\\Documents\\MBAI\\Business Analytics\\FlaskProjects\\Master Code (BA)\\04Regression\\TimeSeveritySlice.csv"
destinationFolder = "C:\\Users\\afeen\\Documents\\MBAI\\Business Analytics\\FlaskProjects\\Master Code (BA)\\04Regression"

# Read the CSV file
dfTime= pd.read_csv(TimeSeveritySlicePath, low_memory=False)

# Make column for SevereInjury:Fatal/Major = 1, Minor/Minimal = 0
dfTime['SevereInjury'] = np.where(dfTime['SeverityOfInjury'].isin(['Fatal', 'Major']), 1, 0)

# print(df['SeverityOfInjury'].value_counts())
# print(df['SevereInjury'].value_counts())

# identify dummy variable columns
peakCols = [c for c in dfTime.columns if c.startswith('TimePeakOffPeak_')]
seasonCols = [c for c in dfTime.columns if c.startswith('TimeSeason_')]
timeRangeCols = [c for c in dfTime.columns if c.startswith('TimeRange_')]
monthCols = [c for c in dfTime.columns if c.startswith('TimeMonth_')]
hourCols = [c for c in dfTime.columns if c.startswith('TimeHour_')]

# baseline have already been dropped in Wrangler.ipynb

print ("Time peak/off-peak dummies:", peakCols[:5],"...total:", len(peakCols))
print ("Time season dummies:", seasonCols[:5],"...total:", len(seasonCols))
print ("Time range dummies:", timeRangeCols[:5],"...total:", len(timeRangeCols))
print ("Time month dummies:", monthCols[:5],"...total:", len(monthCols))
print ("Time hour dummies:", hourCols[:5],"...total:", len(hourCols))

# ModelA: How does time peak/off-peak influence the probability of severe injuries?
formulaA = 'SevereInjury ~ ' + ' + '.join(peakCols)
modelA = smf.logit(formula=formulaA, data=dfTime).fit()
print("\n Model A: Time Peak/Off-Peak vs Severe Injuries \n")
print(modelA.summary())

# Save model summary to csv file
with open(os.path.join(destinationFolder, "TimeModelA_Stats.csv"), 'w') as f:
    f.write(str(modelA.summary()))

# ModelB: how does season influence the probability of severe injuries?
formulaB = 'SevereInjury ~ ' + ' + '.join(seasonCols)
modelB = smf.logit(formula=formulaB, data=dfTime).fit()
print("\n Model B: Time Season vs Severe Injuries \n")
print(modelB.summary())

# Save model summary to csv file
with open(os.path.join(destinationFolder, "TimeModelB_Stats.csv"), 'w') as f:
    f.write(str(modelB.summary()))

# ModelC: how does month influence the probability of severe injuries?
formulaC = 'SevereInjury ~ ' + ' + '.join(monthCols)
modelC = smf.logit(formula=formulaC, data=dfTime).fit()
print("\n Model C: Time Month vs Severe Injuries \n")
print(modelC.summary())

# Save model summary to csv file
with open(os.path.join(destinationFolder, "TimeModelC_Stats.csv"), 'w') as f:
    f.write(str(modelC.summary()))

# ModelD: how does hour influence the probability of severe injuries?
formulaD = 'SevereInjury ~ ' + ' + '.join(hourCols)
modelD = smf.logit(formula=formulaD, data=dfTime).fit()
print("\n Model D: Time Hour vs Severe Injuries \n")
print(modelD.summary())

# Save model summary to csv file
with open(os.path.join(destinationFolder, "TimeModelD_Stats.csv"), 'w') as f:
    f.write(str(modelD.summary()))


# ModelE: how does time range influence the probability of severe injuries?
formulaE = 'SevereInjury ~ ' + ' + '.join(timeRangeCols)
modelE = smf.logit(formula=formulaE, data=dfTime).fit()
print("\n Model E: Time Range vs Severe Injuries \n")
print(modelE.summary())

# Save model summary to csv file
with open(os.path.join(destinationFolder, "TimeModelE_Stats.csv"), 'w') as f:
    f.write(str(modelE.summary()))

# Function for Odds Ratios and Confidence Intervals
# the Odd Ratios and Summary function above will give the same results.
def odds_ratios_and_ci(whichModel):
    params = whichModel.params
    conf = whichModel.conf_int()
    out = pd.DataFrame({
        # Odds Ratios
        "OR": np.exp(params),
        # Confidence Intervals
        "2.5%": np.exp(conf[0]),
        "97.5%": np.exp(conf[1]),
        # p-values
        "pval": whichModel.pvalues
    })
    return out.sort_values(by="OR", ascending=False)

# Function Predicted probabilities for each involvement dummy (set one = 1, others = 0; hold rest at means)

# def predicted_probabilities(whichModel, dummy_cols):
#     # Get the mean values of the continuous variables
#     means = dfUser.mean()
#     # Create a DataFrame to hold the predicted probabilities
#     preds = pd.DataFrame(index=dummy_cols)
#     for col in dummy_cols:
#         # Set the current dummy variable to 1 and others to 0
#         X = pd.DataFrame(0, index=np.arange(1), columns=dummy_cols)
#         X[col] = 1
#         # Add the mean values of the continuous variables
#         for var in means.index:
#             if var not in dummy_cols:
#                 X[var] = means[var]
#         # Get the predicted probabilities
#         preds[col] = whichModel.predict(X)
#     return preds

# Predicted probability for each involvement dummy (set one=1, others=0; all other dummies=0)
def group_pred_by_singleton(whichModel, whichColumns, group_name="Group"):
    # create baseline scenario - set all dummy variables to 0 (reference categories). I will turn on what I want to test
    base = {col: 0 for col in whichModel.model.exog_names if col not in ["Intercept"]}
    # list to store prediction results
    results = []
    for g in whichColumns:
        # creates a copy to avoid modifying the original baseline
        scenario = base.copy()
        # Set only the current group dummy to 1, others stay 0, allowing me to loop through each dummy variable set it to 1 and then leave the others at 0
        scenario[g] = 1
        prob = whichModel.predict(pd.DataFrame([scenario]))[0]
        results.append({group_name: g, "PredProb_Severe": prob})
    return pd.DataFrame(results).sort_values("PredProb_Severe", ascending=False)

#Print and save Predicted probabilities for Models A and Model B
print("\n=== Predicted probability of severe injury by Peak/Off-Peak ===")
predProbPeak= group_pred_by_singleton(modelA, peakCols, group_name="PeakOffPeak")
display(predProbPeak)
predProbPeak.to_csv(os.path.join(destinationFolder, "TimeModelA_Stats.csv"),  mode='a', header=True,index=False)

print("\n=== Predicted probability of severe injury by Season ===")
predProb_Season = group_pred_by_singleton(modelB, seasonCols, group_name="Season")
display(predProb_Season)
predProb_Season.to_csv(os.path.join(destinationFolder, "TimeModelB_Stats.csv"), mode='a', header=True, index=False)

print("\n=== Predicted probability of severe injury by Month ===")
predProb_Month = group_pred_by_singleton(modelC, monthCols, group_name="Month")
display(predProb_Month)
predProb_Month.to_csv(os.path.join(destinationFolder, "TimeModelC_Stats.csv"), mode='a', header=True, index=False)

print("\n=== Predicted probability of severe injury by Hour ===")
predProb_Hour = group_pred_by_singleton(modelD, hourCols, group_name="Hour")
display(predProb_Hour)
predProb_Hour.to_csv(os.path.join(destinationFolder, "TimeModelD_Stats.csv"), mode='a', header=True, index=False)

print("\n=== Predicted probability of severe injury by TimeRange ===")
predProb_TimeRange = group_pred_by_singleton(modelE, timeRangeCols, group_name="TimeRange")
display(predProb_TimeRange)
predProb_TimeRange.to_csv(os.path.join(destinationFolder, "TimeModelE_Stats.csv"), mode='a', header=True, index=False)


# Print and save outputs of odds ratios
modelA_or_ci = odds_ratios_and_ci(modelA)
print("\n=== Odds Ratios for Model A (Peak) ===")
display(modelA_or_ci)
modelA_or_ci.to_csv(os.path.join(destinationFolder, "TimeModelA_Stats.csv"), mode='a', header=True, index=False)

modelB_or_ci = odds_ratios_and_ci(modelB)
print("\n=== Odds Ratios for Model B (Season) ===")
display(modelB_or_ci)
modelB_or_ci.to_csv(os.path.join(destinationFolder, "TimeModelB_Stats.csv"), mode='a', header=True, index=False)

modelC_or_ci = odds_ratios_and_ci(modelC)
print("\n=== Odds Ratios for Model C (Month) ===")
display(modelC_or_ci)
modelC_or_ci.to_csv(os.path.join(destinationFolder, "TimeModelC_Stats.csv"), mode='a', header=True, index=False)

modelD_or_ci = odds_ratios_and_ci(modelD)
print("\n=== Odds Ratios for Model D (Hour) ===")
display(modelD_or_ci)
modelD_or_ci.to_csv(os.path.join(destinationFolder, "TimeModelD_Stats.csv"), mode='a', header=True, index=False)

modelE_or_ci = odds_ratios_and_ci(modelE)
print("\n=== Odds Ratios for Model E (TimeRange) ===")
display(modelE_or_ci)
modelE_or_ci.to_csv(os.path.join(destinationFolder, "TimeModelE_Stats.csv"), mode='a', header=True, index=False)


# # wet-dark predicted probability
# # Fit logistic regression model

# # formulaC = 'SevereInjury ~ ' + ' + '.join(envLightCondCols)
# # modelC = smf.logit(formula=formulaC, data=dfEnv).fit()
# # print("\n Model C: Wet-DDark vs Severe Injuries \n")
# # print(modelC.summary())

# formulaC="""
#     SevereInjury ~ EnvLightingCondition_Dark 
#                    + EnvLightingCondition_Dark__artificial
#                    + EnvLightingCondition_Dusk
#                    + EnvLightingCondition_Dusk__artificial
#                    + EnvLightingCondition_Dawn
#                    + EnvLightingCondition_Dawn__artificial
#                    + EnvRoadSurfaceCondition_Wet
#                    + EnvRoadSurfaceCondition_Ice
#                    + EnvRoadSurfaceCondition_Packed_Snow
#                    + EnvRoadSurfaceCondition_Slush
#                    + EnvRoadSurfaceCondition_Loose_Snow
#                    + EnvRoadSurfaceCondition_Loose_Sand_or_Gravel
#                    + EnvRoadSurfaceCondition_Spilled_liquid
#                    + EnvRoadSurfaceCondition_Other
#     """
# modelC = smf.logit(
#     formula=formulaC,
#     data=dfEnv
# ).fit()

# # Create input for wet-dark conditions (baseline: Daylight, Dry)
# wet_dark = pd.DataFrame({
#     "EnvLightingCondition_Dark": [1],
#     "EnvLightingCondition_Dark__artificial": [0],
#     "EnvLightingCondition_Dawn": [0],
#     "EnvLightingCondition_Dawn__artificial": [0],
#     "EnvLightingCondition_Daylight__artificial": [0],
#     "EnvLightingCondition_Dusk": [0],
#     "EnvLightingCondition_Dusk__artificial": [0],
#     "EnvLightingCondition_Other": [0],
#     "EnvRoadSurfaceCondition_Ice": [0],
#     "EnvRoadSurfaceCondition_Loose_Sand_or_Gravel": [0],
#     "EnvRoadSurfaceCondition_Loose_Snow": [0],
#     "EnvRoadSurfaceCondition_Other": [0],
#     "EnvRoadSurfaceCondition_Packed_Snow": [0],
#     "EnvRoadSurfaceCondition_Slush": [0],
#     "EnvRoadSurfaceCondition_Spilled_liquid": [0],
#     "EnvRoadSurfaceCondition_Wet": [1]
# })

# # Predict probability for Wet–Dark
# pred_prob_wet_dark = modelC.predict(wet_dark)
# print("\nPredicted Probability of Severe Collision (Wet–Dark):", float(pred_prob_wet_dark))
# pred_prob_wet_dark.to_csv(os.path.join(destinationFolder, "EnvModelC_Stats.csv"),  mode='a', header=True,index=False)

# # Find the deadliest coobminations of lighting and road surface conditions

# # #  Generate all combinations of lighting × road surface conditions
# # lightingCols = [
# #     "EnvLightingCondition_Dark",
# #     "EnvLightingCondition_Dark__artificial",
# #     "EnvLightingCondition_Dusk",
# #     "EnvLightingCondition_Dusk__artificial",
# #     "EnvLightingCondition_Dawn",
# #     "EnvLightingCondition_Dawn__artificial"
# # ]

# # road_vars = [
# #     "EnvRoadSurfaceCondition_Wet",
# #     "EnvRoadSurfaceCondition_Ice",
# #     "EnvRoadSurfaceCondition_Packed_Snow",
# #     "EnvRoadSurfaceCondition_Slush",
# #     "EnvRoadSurfaceCondition_Loose_Snow",
# #     "EnvRoadSurfaceCondition_Loose_Sand_or_Gravel",
# #     "EnvRoadSurfaceCondition_Spilled_liquid",
# #     "EnvRoadSurfaceCondition_Other"
# # ]

# combinations = list(product(envLightCondCols, envRoadSurfCols))

# # Create DataFrame for each combination and predict probabilities
# results = []

# for light, road in combinations:
#     # Set all dummy vars = 0
#     row = {v: 0 for v in envLightCondCols + envRoadSurfCols}
    
#     # Turn on this combination
#     row[light] = 1
#     row[road] = 1
    
#     # Predict probability
#     prob = modelC.predict(pd.DataFrame([row]))[0]
    
#     results.append({
#         "LightingCondition": light,
#         "RoadSurfaceCondition": road,
#         "PredictedProbability": prob
#     })

# # Create a results DataFrame and find the max
# pred_df = pd.DataFrame(results)
# most_dangerous = pred_df.sort_values("PredictedProbability", ascending=False).head(1)
# print("Most Dangerous Combination:\n", most_dangerous)
# most_dangerous.to_csv(os.path.join(destinationFolder, "EnvModelC_Stats.csv"),  mode='a', header=True,index=False)

Time peak/off-peak dummies: ['TimePeakOffPeak_OFF_PEAK'] ...total: 1
Time season dummies: ['TimeSeason_WINTER'] ...total: 1
Time range dummies: ['TimeRange_15_00_to_17_59', 'TimeRange_18_00_to_20_59', 'TimeRange_21_00_to_23_59', 'TimeRange_3_00_to_5_59', 'TimeRange_6_00_to_8_59'] ...total: 7
Time month dummies: ['TimeMonth_April', 'TimeMonth_August', 'TimeMonth_December', 'TimeMonth_February', 'TimeMonth_July'] ...total: 11
Time hour dummies: ['TimeHour_0', 'TimeHour_1', 'TimeHour_2', 'TimeHour_3', 'TimeHour_4'] ...total: 23
Optimization terminated successfully.
         Current function value: 0.574771
         Iterations 5

 Model A: Time Peak/Off-Peak vs Severe Injuries

                           Logit Regression Results
==============================================================================
Dep. Variable:           SevereInjury   No. Observations:                10044
Model:                          Logit   Df Residuals:                    10042
Method:                           MLE   Df Model:                            1
Date:                Mon, 06 Oct 2025   Pseudo R-squ.:                0.001439
Time:                        15:13:20   Log-Likelihood:                -5773.0
converged:                       True   LL-Null:                       -5781.3
Covariance Type:            nonrobust   LLR p-value:                 4.523e-05
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
Intercept                    1.1369      0.034     32.972      0.000       1.069       1.204
TimePeakOffPeak_OFF_PEAK    -0.1864      0.046     -4.070      0.000      -0.276      -0.097
============================================================================================
Optimization terminated successfully.
         Current function value: 0.575577
         Iterations 5

 Model B: Time Season vs Severe Injuries

                           Logit Regression Results
==============================================================================
Dep. Variable:           SevereInjury   No. Observations:                10044
Model:                          Logit   Df Residuals:                    10042
Method:                           MLE   Df Model:                            1
Date:                Mon, 06 Oct 2025   Pseudo R-squ.:               3.828e-05
Time:                        15:13:20   Log-Likelihood:                -5781.1
converged:                       True   LL-Null:                       -5781.3
Covariance Type:            nonrobust   LLR p-value:                    0.5059
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept             1.0410      0.026     40.806      0.000       0.991       1.091
TimeSeason_WINTER    -0.0371      0.056     -0.666      0.505      -0.146       0.072
=====================================================================================
Optimization terminated successfully.
         Current function value: 0.574107
         Iterations 5

 Model C: Time Month vs Severe Injuries

                           Logit Regression Results
==============================================================================
Dep. Variable:           SevereInjury   No. Observations:                10044
Model:                          Logit   Df Residuals:                    10032
Method:                           MLE   Df Model:                           11
Date:                Mon, 06 Oct 2025   Pseudo R-squ.:                0.002592
Time:                        15:13:20   Log-Likelihood:                -5766.3
converged:                       True   LL-Null:                       -5781.3
Covariance Type:            nonrobust   LLR p-value:                  0.001605
=======================================================================================
                          coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept               0.9045      0.083     10.899      0.000       0.742       1.067
TimeMonth_April        -0.1181      0.116     -1.016      0.310      -0.346       0.110
TimeMonth_August        0.0759      0.109      0.700      0.484      -0.137       0.289
TimeMonth_December      0.1994      0.118      1.694      0.090      -0.031       0.430
TimeMonth_February      0.0947      0.124      0.765      0.444      -0.148       0.337
TimeMonth_July          0.0845      0.110      0.766      0.443      -0.132       0.301
TimeMonth_June          0.1167      0.110      1.064      0.287      -0.098       0.332
TimeMonth_March         0.1329      0.121      1.098      0.272      -0.104       0.370
TimeMonth_May           0.0527      0.113      0.466      0.641      -0.169       0.274
TimeMonth_November      0.3871      0.119      3.261      0.001       0.154       0.620
TimeMonth_October       0.3083      0.114      2.712      0.007       0.086       0.531
TimeMonth_September     0.1875      0.110      1.700      0.089      -0.029       0.404
=======================================================================================
Optimization terminated successfully.
         Current function value: 0.572563
         Iterations 5

 Model D: Time Hour vs Severe Injuries

                           Logit Regression Results
==============================================================================
Dep. Variable:           SevereInjury   No. Observations:                10044
Model:                          Logit   Df Residuals:                    10020
Method:                           MLE   Df Model:                           23
Date:                Mon, 06 Oct 2025   Pseudo R-squ.:                0.005274
Time:                        15:13:20   Log-Likelihood:                -5750.8
converged:                       True   LL-Null:                       -5781.3
Covariance Type:            nonrobust   LLR p-value:                 2.753e-05
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept       0.9930      0.106      9.407      0.000       0.786       1.200
TimeHour_0     -0.2053      0.156     -1.318      0.187      -0.511       0.100
TimeHour_1     -0.0926      0.172     -0.538      0.591      -0.430       0.245
TimeHour_2     -0.1522      0.166     -0.919      0.358      -0.477       0.172
TimeHour_3     -0.3164      0.166     -1.901      0.057      -0.643       0.010
TimeHour_4     -0.0164      0.242     -0.068      0.946      -0.491       0.458
TimeHour_5     -0.1327      0.192     -0.690      0.490      -0.510       0.244
TimeHour_6      0.2138      0.170      1.257      0.209      -0.120       0.547
TimeHour_7      0.3642      0.178      2.044      0.041       0.015       0.713
TimeHour_8      0.3088      0.168      1.835      0.067      -0.021       0.639
TimeHour_9      0.2288      0.160      1.428      0.153      -0.085       0.543
TimeHour_10     0.0770      0.154      0.499      0.618      -0.225       0.379
TimeHour_11     0.1628      0.155      1.050      0.294      -0.141       0.467
TimeHour_13    -0.1709      0.144     -1.185      0.236      -0.454       0.112
TimeHour_14    -0.0547      0.142     -0.384      0.701      -0.333       0.224
TimeHour_15     0.2226      0.146      1.529      0.126      -0.063       0.508
TimeHour_16    -0.0937      0.140     -0.669      0.504      -0.368       0.181
TimeHour_17     0.1374      0.140      0.980      0.327      -0.138       0.412
TimeHour_18     0.2837      0.142      1.998      0.046       0.005       0.562
TimeHour_19     0.2087      0.146      1.432      0.152      -0.077       0.494
TimeHour_20    -0.1024      0.140     -0.730      0.465      -0.377       0.173
TimeHour_21     0.0553      0.147      0.376      0.707      -0.233       0.343
TimeHour_22     0.0560      0.151      0.372      0.710      -0.239       0.351
TimeHour_23    -0.2074      0.151     -1.371      0.170      -0.504       0.089
===============================================================================
Optimization terminated successfully.
         Current function value: 0.573778
         Iterations 5

 Model E: Time Range vs Severe Injuries

                           Logit Regression Results
==============================================================================
Dep. Variable:           SevereInjury   No. Observations:                10044
Model:                          Logit   Df Residuals:                    10036
Method:                           MLE   Df Model:                            7
Date:                Mon, 06 Oct 2025   Pseudo R-squ.:                0.003163
Time:                        15:13:20   Log-Likelihood:                -5763.0
converged:                       True   LL-Null:                       -5781.3
Covariance Type:            nonrobust   LLR p-value:                 5.644e-06
==============================================================================================
                                 coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                      0.9158      0.057     15.956      0.000       0.803       1.028
TimeRange_15_00_to_17_59       0.1626      0.079      2.053      0.040       0.007       0.318
TimeRange_18_00_to_20_59       0.2070      0.080      2.600      0.009       0.051       0.363
TimeRange_21_00_to_23_59       0.0521      0.084      0.622      0.534      -0.112       0.216
TimeRange_3_00_to_5_59        -0.1248      0.108     -1.158      0.247      -0.336       0.086
TimeRange_6_00_to_8_59         0.3707      0.097      3.817      0.000       0.180       0.561
TimeRange_9_00_to_11_59        0.2310      0.088      2.627      0.009       0.059       0.403
TimeRange_Midnight_to_2_59    -0.0790      0.092     -0.856      0.392      -0.260       0.102
==============================================================================================

=== Predicted probability of severe injury by Peak/Off-Peak ===

                PeakOffPeak  PredProb_Severe
0  TimePeakOffPeak_OFF_PEAK         0.721207

=== Predicted probability of severe injury by Season ===

              Season  PredProb_Severe
0  TimeSeason_WINTER         0.731825

=== Predicted probability of severe injury by Month ===

                  Month  PredProb_Severe
8    TimeMonth_November         0.784409
9     TimeMonth_October         0.770789
2    TimeMonth_December         0.750978
10  TimeMonth_September         0.748759
6       TimeMonth_March         0.738346
5        TimeMonth_June         0.735206
3    TimeMonth_February         0.730897
4        TimeMonth_July         0.728884
1      TimeMonth_August         0.727184
7         TimeMonth_May         0.722550
0       TimeMonth_April         0.687055

=== Predicted probability of severe injury by Hour ===

           Hour  PredProb_Severe
7    TimeHour_7         0.795302
8    TimeHour_8         0.786127
17  TimeHour_18         0.781874
9    TimeHour_9         0.772379
14  TimeHour_15         0.771277
6    TimeHour_6         0.769716
18  TimeHour_19         0.768817
11  TimeHour_11         0.760563
16  TimeHour_17         0.755906
10  TimeHour_10         0.744578
21  TimeHour_22         0.740576
20  TimeHour_21         0.740443
4    TimeHour_4         0.726415
13  TimeHour_14         0.718750
1    TimeHour_1         0.711027
15  TimeHour_16         0.710801
19  TimeHour_20         0.708995
5    TimeHour_5         0.702703
2    TimeHour_2         0.698630
12  TimeHour_13         0.694672
0    TimeHour_0         0.687324
22  TimeHour_23         0.686869
3    TimeHour_3         0.662963

=== Predicted probability of severe injury by TimeRange ===

                    TimeRange  PredProb_Severe
4      TimeRange_6_00_to_8_59         0.783559
5     TimeRange_9_00_to_11_59         0.758929
1    TimeRange_18_00_to_20_59         0.754505
0    TimeRange_15_00_to_17_59         0.746193
2    TimeRange_21_00_to_23_59         0.724702
6  TimeRange_Midnight_to_2_59         0.697802
3      TimeRange_3_00_to_5_59         0.688057

=== Odds Ratios for Model A (Peak) ===

                                OR      2.5%     97.5%           pval
Intercept                 3.117012  2.913327  3.334937  2.034320e-238
TimePeakOffPeak_OFF_PEAK  0.829925  0.758664  0.907879   4.703668e-05

=== Odds Ratios for Model B (Season) ===

                         OR      2.5%     97.5%      pval
Intercept          2.832131  2.694002  2.977342  0.000000
TimeSeason_WINTER  0.963552  0.863875  1.074729  0.505143

=== Odds Ratios for Model C (Month) ===

                           OR      2.5%     97.5%          pval
Intercept            2.470588  2.099740  2.906934  1.160612e-27
TimeMonth_November   1.472693  1.167021  1.858429  1.109310e-03
TimeMonth_October    1.361130  1.089294  1.700802  6.679388e-03
TimeMonth_December   1.220643  0.969139  1.537416  9.032713e-02
TimeMonth_September  1.206286  0.971779  1.497385  8.905311e-02
TimeMonth_March      1.142173  0.900814  1.448201  2.724078e-01
TimeMonth_June       1.123828  0.906373  1.393454  2.873308e-01
TimeMonth_February   1.099353  0.862463  1.401309  4.442763e-01
TimeMonth_July       1.088187  0.876654  1.350761  4.434915e-01
TimeMonth_August     1.078885  0.872147  1.334629  4.841960e-01
TimeMonth_May        1.054103  0.844643  1.315507  6.410932e-01
TimeMonth_April      0.888636  0.707646  1.115917  3.095877e-01

=== Odds Ratios for Model D (Hour) ===

                   OR      2.5%     97.5%          pval
Intercept    2.699187  2.194741  3.319576  5.112989e-21
TimeHour_7   1.439413  1.015084  2.041122  4.095557e-02
TimeHour_8   1.361771  0.979104  1.893999  6.657924e-02
TimeHour_18  1.327995  1.005474  1.753970  4.567104e-02
TimeHour_9   1.257141  0.918236  1.721130  1.533607e-01
TimeHour_15  1.249300  0.939184  1.661815  1.262739e-01
TimeHour_6   1.238323  0.887221  1.728368  2.089163e-01
TimeHour_19  1.232068  0.926029  1.639248  1.520097e-01
TimeHour_11  1.176825  0.868471  1.594662  2.935853e-01
TimeHour_17  1.147299  0.871514  1.510354  3.272942e-01
TimeHour_10  1.079990  0.798121  1.461405  6.180093e-01
TimeHour_22  1.057615  0.787279  1.420779  7.099433e-01
TimeHour_21  1.056879  0.792303  1.409804  7.066905e-01
TimeHour_4   0.983693  0.612047  1.581010  9.458570e-01
TimeHour_14  0.946787  0.716419  1.251231  7.006855e-01
TimeHour_1   0.911581  0.650476  1.277495  5.908181e-01
TimeHour_16  0.910582  0.691988  1.198228  5.036315e-01
TimeHour_20  0.902629  0.685594  1.188370  4.653516e-01
TimeHour_5   0.875685  0.600592  1.276778  4.902071e-01
TimeHour_2   0.858844  0.620863  1.188046  3.580184e-01
TimeHour_13  0.842909  0.635343  1.118285  2.360730e-01
TimeHour_0   0.814393  0.600182  1.105058  1.873525e-01
TimeHour_23  0.812670  0.604159  1.093143  1.702994e-01
TimeHour_3   0.728750  0.525854  1.009932  5.735427e-02

=== Odds Ratios for Model E (TimeRange) ===

                                  OR      2.5%     97.5%          pval
Intercept                   2.498824  2.232945  2.796360  2.607287e-57
TimeRange_6_00_to_8_59      1.448759  1.197667  1.752491  1.348602e-04
TimeRange_9_00_to_11_59     1.259852  1.060416  1.496797  8.610897e-03
TimeRange_18_00_to_20_59    1.229937  1.052292  1.437570  9.311718e-03
TimeRange_15_00_to_17_59    1.176554  1.007388  1.374127  4.008245e-02
TimeRange_21_00_to_23_59    1.053469  0.893888  1.241538  5.342633e-01
TimeRange_Midnight_to_2_59  0.924071  0.771262  1.107156  3.918764e-01
TimeRange_3_00_to_5_59      0.882701  0.714724  1.090157  2.466716e-01